#[customtest]
#title = '自定义测试'
#column = 'test'
#ctype = 'custom'
#column_name = ['日期', '余额加权的隐含波动率']
#[customtest.conditions]
#main = ['SELECT SUM("债券余额" * "隐含波动率") / SUM("债券余额")']

[fit]
title = '拟合示例'
column = '转股溢价率(%)'
ctype = 'median'
[fit.conditions]
main = ["\"债券类型\" = '可转债'", '"转换价值" > 100', '"转换价值" <= 110']
ratio_total = ["\"债券类型\" = '可转债'"]
[fit.fit_config] # 拟合配置
enable_fitting = true # 启用拟合功能
min_data_threshold = 100 # 当筛选后数据量少于此值时触发拟合
fit_type = "polynomial"  # 拟合算法类型可选: linear, polynomial, exponential, logarithmic, power
historical_files_count = 10 # 拟合时使用的历史数据文件数量
[fit.fit_config.params] # 拟合参数
polynomial_degree = 3 # 多项式拟合的阶数（仅当 fit_type = "polynomial" 时有效）
[fit.fit_config.quality] # 拟合质量控制
min_r_squared = 0.6 # 最小R²值，低于此值将标记为低质量拟合
fallback_on_poor_fit = true # 低质量拟合时是否回退到原始数据
include_quality_info = true # 是否在输出中包含拟合质量信息
[fit.fit_config.fit_conditions] # 拟合筛选条件
main = ["\"债券类型\" = '可转债'", '"转换价值" > 80', '"转换价值" <= 130']
[fit.fit_config.exclude_conditions] # 拟合排除条件 - 从拟合筛选条件中排除这些数据
main = ['"转换价值" = 100'] # 排除转换价值等于100的数据
[fit.fit_config.predict_conditions] # 预测条件 - 预测在指定列值条件下的目标列值
predict_column = "转换价值" # 预测基于的列名（X轴）
predict_value = 100 # 预测基于的列值（X值）
target_column = "转股溢价率(%)" # 目标预测列名（Y轴，通常与主column相同）
