sync_date = "20250127"

[column_name]
ratio = ["日期", "筛选后数量", "转债总数"]
median = ["日期", "中位数"]
avg = ["日期", "平均数"]
max = ["日期", "最大值"]
min = ["日期", "最小值"]
std_0 = ["日期", "有偏样本标准差"]
std_1 = ["日期", "无偏样本标准差"]
check = ["数据表", "缺失数据"]
fit_median = ["日期", "拟合中位数", "拟合质量(R²)"]
fit_avg = ["日期", "拟合平均数", "拟合质量(R²)"]
fit_max = ["日期", "拟合最大值", "拟合质量(R²)"]
fit_min = ["日期", "拟合最小值", "拟合质量(R²)"]
